{% set name = "zk" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mickael-menu/zk/archive/v{{ version }}.tar.gz
  sha256: bd96f93d50e2e72ce05f36c3dab5b7942ae205756f26d4c68ba2a7ccc783abc8

build:
  number: 1

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - icu  # [linux]
    - sqlite  # [linux]

test:
  commands:
    - zk --help

about:
  home: https://github.com/mickael-menu/zk
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Plain text note-taking assistant
  dev_url: https://github.com/mickael-menu/zk

extra:
  recipe-maintainers:
    - danielnachun
