schema_version: 1

context:
  version: "0.15.4"

package:
  name: zk
  version: ${{ version }}

source:
  url: https://github.com/zk-org/zk/archive/v${{ version }}.tar.gz
  sha256: 024b5a1615c8ac1924ec3338b36031c36131bad5de77dcce05adce35659b7489

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - if: linux
      then:
        - icu
        - sqlite

tests:
  - script:
      - zk --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Plain text note-taking assistant
  homepage: https://github.com/zk-org/zk
  repository: https://github.com/zk-org/zk

extra:
  recipe-maintainers:
    - danielnachun
