schema_version: 1

context:
  version: "0.15.3"

package:
  name: zk
  version: ${{ version }}

source:
  url: https://github.com/zk-org/zk/archive/v${{ version }}.tar.gz
  sha256: 3cd5b011db7b587fd53d99040d117b3f52f0dd8524bae2a35bc9ea4b9590e754

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - if: linux
      then:
        - icu
        - sqlite

tests:
  - script:
      - zk --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Plain text note-taking assistant
  homepage: https://github.com/zk-org/zk
  repository: https://github.com/zk-org/zk

extra:
  recipe-maintainers:
    - danielnachun
