schema_version: 1

context:
  version: "0.15.2"

package:
  name: zk
  version: ${{ version }}

source:
  url: https://github.com/zk-org/zk/archive/v${{ version }}.tar.gz
  sha256: cd8524ea3be81784336706f68edaafe9b4f21d05e0d7a968065cf685e9afefc1

build:
  number: 1

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
  host:
    - if: linux
      then:
        - icu
        - sqlite

tests:
  - script:
      - zk --help

about:
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: Plain text note-taking assistant
  homepage: https://github.com/zk-org/zk
  repository: https://github.com/zk-org/zk

extra:
  recipe-maintainers:
    - danielnachun
